### ISSUE TITLE
Depreciated Issue In Flutter 3.3.9

### ISSUE THREAD

**Issue by maxgeorge21** [floranguyen0/mmas-money-tracker#2]
Hello Flora,

I am apreciated you making this complex and awesome app for open source code, but seem when i am trying to run this app and running pub get for flutter version 3.3.9. Can you make this app running in latest version? Thanks

**Comment by Vikkybliz** [comment]
Can I take up this task?

**Comment by floranguyen0** [comment]
Sure, much appreciated!

**Comment by aritroo** [comment]
Hello @floranguyen0  I had fixed this issue and made a Pull request ...if the fix is proper please merge it.

**Comment by floranguyen0** [comment]
Hi Aritoo, I appreciate you contributing to the repo. But I believe your PR is irrelevant to this issue

**Comment by floranguyen0** [comment]
Hi @aritroo, I appreciate you contributing to the repo. But I believe your PR is irrelevant to this issue.

**Comment by floranguyen0** [comment]
@maxgeorge21 I have fixed that. Does it work on your machine?
