### ISSUE TITLE
Multiple issues / code smelles

### ISSUE THREAD

**Issue by VladBalan5** [floranguyen0/mmas-money-tracker#6]
Hello,

I ran a static code analysis and I found 16 minor issues.
I made 2 screenshots with al the issues and I hope it will help.
![Issue1](https://user-images.githubusercontent.com/85182055/233853393-c6fe338a-7c0b-492a-8d97-6ca726f3bdf2.png)
![Issue2](https://user-images.githubusercontent.com/85182055/233853401-011efd41-c620-470a-9fc1-7a1085af26d2.png)

**Comment by Dhruv-1312** [comment]
Hi is this issue still open?
I would like to work on this.
Can you please assign me.
Thankyou!

**Comment by Priyammm05** [comment]
Hi, is this issue still open to work?
If its is then can you please assign me. I would like to work on this.
Thankyou!
